### PR TITLE
Update missing enums & spelling

### PR DESCRIPTION
**Pull request by vladdeSV**
Adds ability `OpponentBones` and appearance behaviour `RedEmission`, as well as fixing some some minor spelling mistakes.

### CODE REVIEW

**Comment by MADH95** [comment]
AlternatingBloodDecal is rendered like the mycologist merge, it's clearer to the user what that represents rather than just repeating the name. If you change that back, I'll merge the commit.

**Comment by vladdeSV** [comment]
> AlternatingBloodDecal is rendered like the mycologist merge

That is not correct. I tested this yesterday, and it acts like the blood decal on the shark.

**Comment by vladdeSV** [comment]
Backing up with an image. This config produces this card.

```json
{
  "modPrefix": "a",
  "name": "a_a",
  "appearanceBehaviour": [
    "AlternatingBloodDecal"
  ]
}
```

proof

**Comment by MADH95** [comment]
Huh, my bad, Is the mychologist one missing then?

**Comment by vladdeSV** [comment]
I am unsure. Unfamiliar with the API; unsure if it's a flag.

AFAIK, the only special with a merged card is that it has the decals fungus and stitches, and the alternating blood decal.

**Pull request merged**
